clinica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('pacientes/', include('pacientes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('reportes/', include('reportes.urls')),
    path('', include('compartido.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pacientes/urls.py
# Django
from django.urls import path

# Vistas

from .views import pacientes, observaciones, turnos
from .views.turnos import TurnosCalendarioView

app_name = 'pacientes'

URLS_PACIENTES = [
    path('', pacientes.Listar.as_view(), name='lista'),
    path('agregar/', pacientes.Agregar.as_view(), name='agregar'),
    path('detalle/<uuid:pk>', pacientes.Detalle.as_view(), name='detalle'),
    path('editar/<uuid:pk>', pacientes.Editar.as_view(), name='editar'),
    path('eliminar/<uuid:pk>', pacientes.Eliminar.as_view(), name='eliminar'),
]

URL_OBSERVACIONES = [
    path('observaciones/<uuid:pk>', observaciones.Listar.as_view(), name='lista_observaciones'),
    path('observaciones/agregar/<uuid:pk>', observaciones.Agregar.as_view(), name='agregar_observacion'),
    path('observaciones/editar/<uuid:pk>', observaciones.Editar.as_view(), name='editar_observacion'),
    path('observaciones/eliminar/<uuid:pk>', observaciones.Eliminar.as_view(), name='eliminar_observacion')
]

URL_TURNOS = [
    path('turnos/', turnos.Listar.as_view(), name='lista_turnos'),
    path('turnos/calendario/', turnos.TurnosCalendarioView.as_view(), name='turnos_calendario'),
    path('turnos/agregar', turnos.Agregar.as_view(), name='agregar_turno'),
    path('turnos/editar/<uuid:pk>', turnos.Editar.as_view(), name='editar_turno'),
    path('turnos/eliminar/<uuid:pk>', turnos.Eliminar.as_view(), name='eliminar_turno')
]

urlpatterns = URLS_PACIENTES + URL_OBSERVACIONES + URL_TURNOS

pacientes/views/observaciones.py
# Django
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Modelos
from ..models import Observacion, Paciente
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioObservacion


class Listar(LoginRequiredMixin, generic.ListView):
    """
    Lista todos las observaciones de un paciente en el sistema. 
    """
    template_name = 'clinica/pacientes/observaciones/lista_observaciones.html'
    context_object_name = 'Observaciones'
    paginate_by = 5
    # page_kwarg

    def get_queryset(self):
        return Observacion.objects.filter(paciente=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        paciente = Paciente.objects.get(id=self.kwargs['pk'])
        contexto = super().get_context_data(**kwargs)
        contexto['pacienteid'] = paciente.id
        contexto['titulo'] = f'Historial clínico de {paciente}'
        contexto['cantidad'] = Observacion.objects.filter(paciente=self.kwargs['pk']).count()
        contexto['volver'] = reverse_lazy('pacientes:detalle', kwargs={'pk':self.kwargs['pk']})
        return contexto


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega una nueva observación al historial de un paciente.
    """
    model = Observacion
    form_class = FormularioObservacion
    template_name = 'clinica/pacientes/observaciones/form_observacion.html'

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Cargo una observación'
        )
        messages.success(
            self.request,
            'Observación cargada!'
        )
        form.instance.paciente = Paciente.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('pacientes:lista_observaciones', kwargs={'pk':self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Agregar nuevo registro de historial'
        contexto['url_volver'] = self.get_success_url
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de una determinada observacion
    """
    model = Observacion
    form_class = FormularioObservacion
    template_name = 'clinica/pacientes/observaciones/form_observacion.html'          

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Modifico una observación'
        )
        messages.success(
            self.request,
            'Observación modificada!'
        )
        paciente = Paciente.objects.get(id=self.request.GET.get('paciente'))
        form.instance.paciente = Paciente.objects.get(pk=paciente.id)
        return super().form_valid(form)

    def get_success_url(self):
        uuid = self.request.GET.get('paciente')
        paciente = Paciente.objects.get(id=uuid)
        return reverse_lazy('pacientes:lista_observaciones', kwargs={'pk': paciente.id})

    def get_context_data(self, **kwargs):
        paciente = Paciente.objects.get(id=self.request.GET.get('paciente'))
        contexto = super().get_context_data(**kwargs)
        contexto['pacienteid'] = paciente.id
        contexto['titulo'] = f'Observación de {self.object.paciente}'
        contexto['url_volver'] = self.get_success_url
        contexto['editar'] = True
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """
    Elimina una observacion del historial de un paciente
    """
    model = Observacion
    template_name = 'componentes/delete.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó una observación'
        )
        messages.success(
            self.request,
            'Observación eliminada!'
        )
        lista = self.request.GET.get('lista')
        return reverse_lazy('pacientes:lista_observaciones', kwargs={'pk': self.object.paciente.id})

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar {self.object.motivo_consulta}'
        contexto['url_volver'] = reverse_lazy('pacientes:lista_observaciones', kwargs={'pk': self.object.paciente.id})
        
        return contexto

pacientes/views/pacientes.py
# Django
from django.db.models import Q
from django.views import generic
from django.contrib import messages
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Modelos
from ..models import Paciente, Turno
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioPaciente


class Listar(LoginRequiredMixin, generic.ListView):
    """
    Lista todos los pacientes cargados en el sistema. 
    """
    template_name = 'clinica/pacientes/lista_pacientes.html'
    context_object_name = 'Pacientes'
    paginate_by = 5
    # page_kwarg

    def get_queryset(self):
        b_query = self.request.GET.get('query')
        b_fecha = self.request.GET.get('fecha')
        if self.request.user.rol == 'M':
            if b_fecha:
                data = []  # Pacientes que fueron atendidos esa fecha por ese doctor
                turnos = Turno.objects.filter(fecha=b_fecha).filter(asistencia='A')
                for turno in turnos:
                    paciente = Paciente.objects.get(id=turno.paciente.id)
                    if paciente.medico == self.request.user:
                        data.append(paciente)
                return data
            if b_query:
                return Paciente.objects.filter(
                    # Busco ocurrencias...
                    Q(nombre__in=b_query.split()) | Q(apellido__in=b_query.split()) |
                    Q(nombre__icontains=b_query.split()[0])  |
                    Q(apellido__icontains=b_query.split()[0])|
                    Q(documento__contains=b_query)
                ).filter(medico=self.request.user.id)
            else:
                return Paciente.objects.filter(medico=self.request.user.id)            
        if b_fecha:
            data = []  # Pacientes que fueron atendidos esa fecha
            turnos = Turno.objects.filter(fecha=b_fecha).filter(asistencia='A')
            for turno in turnos:
                paciente = Paciente.objects.get(id=turno.paciente.id)
                data.append(paciente)
            if len(data)==0:
                messages.error(
                    self.request,
                    f"Ningún paciente fue atendido el dia {b_fecha}"
                )
            return data
        if b_query:
            return Paciente.objects.filter(
                # Busco ocurrencias...
                Q(nombre__in=b_query.split()) | Q(apellido__in=b_query.split()) |
                Q(nombre__icontains=b_query.split()[0])  |
                Q(apellido__icontains=b_query.split()[0])|
                Q(documento__contains=b_query)  
            )
        else:
            return Paciente.objects.all()

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Lista de pacientes'
        contexto['buscar'] = 'Ingresa el nombre de algún paciente o el numero de CI'
        contexto['cantidad'] = Paciente.objects.count()
        return contexto


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega un nuevo paciente y retorna a la lista de pacientes.
    """
    model = Paciente
    form_class = FormularioPaciente
    template_name = 'clinica/pacientes/form_paciente.html'

    def form_valid(self, form):
        registrarActividad(
            self.request, 
            'Cargó un paciente'
        )
        # Mensaje al usuario
        messages.success(
            self.request,
            'Paciente cargado!'
        )
        return super().form_valid(form)

    def get_success_url(self):
        path_previo = self.request.GET.get('prev')
        if path_previo:
            # Si accedemos desde pedidos, volverá a pedidos
            if 'pedidos' in path_previo:
                return reverse_lazy('productos:agregar_pedido')
            # Si accedemos desde cargar turno, volverá a cargar turnos
            if 'turnos' in path_previo:
                return reverse_lazy('pacientes:agregar_turno')
            # Si no, vuelve a lista de pacientes
        else:
            return reverse_lazy('pacientes:lista')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Agregar nuevo paciente'
        contexto['volver'] = self.get_success_url
        return contexto


class Detalle(LoginRequiredMixin, generic.DetailView):
    """ 
    Muestra toda la información de un determinado paciente.
    """
    model = Paciente
    template_name = 'clinica/pacientes/detalle_paciente.html'
    context_object_name = 'Paciente'

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = self.object
        contexto['Historial'] = self.object.observaciones.all().order_by('-created_at')[0:6]
        contexto['cantidad'] = self.object.observaciones.count()
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de un determinado paciente.
    """
    model = Paciente
    form_class = FormularioPaciente
    template_name = 'clinica/pacientes/form_paciente.html'

    def get_success_url(self):
        registrarActividad(
            self.request, 
            'Modificó un paciente'
        )
        # Mensaje al usuario
        messages.success(
            self.request,
            'Paciente modificado!'
        )
        return reverse_lazy('pacientes:lista')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Editar a {self.object}'
        contexto['volver'] = reverse_lazy('pacientes:detalle', kwargs={'pk':self.kwargs['pk']})
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """ 
    Elimina un determinado paciente del sistema.
    """
    model = Paciente
    template_name = 'componentes/delete.html'
    
    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó un paciente'
        )
        # Mensaje al usuario
        messages.success(
            self.request,
            'Paciente eliminado!'
        )
        return reverse_lazy('pacientes:lista')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar a {self.object}'
        contexto['url_volver'] = reverse_lazy('pacientes:lista')
        return contexto

pacientes/views/turnos.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils import timezone
from django.views import generic
from django.views import View
from datetime import datetime, timedelta
from calendar import HTMLCalendar
from django.utils.safestring import mark_safe
from django.shortcuts import render
from django.http import JsonResponse


# Modelos
from ..models import Turno
from usuarios.models import registrarActividad

# Formularios
from ..forms import FormularioTurno

class Listar(LoginRequiredMixin, generic.ListView):
    """
    Lista todos los turnos. 
    """
    model = Turno
    template_name = 'clinica/turnos/lista_turnos.html'
    context_object_name = 'Turnos'
    paginate_by = 5
    # page_kwarg

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Lista de turnos'
        contexto['buscar'] = 'Ingresa el nombre de alǵun paciente o una fecha'
        contexto['hoy'] = Turno.objects.filter(fecha=timezone.now()).filter(asistencia='P')
        return contexto


class Agregar(LoginRequiredMixin, generic.CreateView):
    """ 
    Agrega un nuevo turno y retorna a la lista de turnos.
    """
    model = Turno
    form_class = FormularioTurno
    template_name = 'clinica/turnos/form_turno.html'
    success_url = reverse_lazy('pacientes:lista_turnos')


    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Cargó un turno'
        )
        messages.success(
            self.request,
            'Turno cargado!'
        )
        form.instance.asistencia = Turno.ASISTIO_OPCIONES[0][0]  # P - PENDIENTE
        if not form.instance.fecha:
            form.instance.fecha = timezone.now()
        return super().form_valid(form)
 
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = 'Registrar un nuevo turno'
        contexto['volver'] = self.success_url
        return contexto


class Editar(LoginRequiredMixin, generic.UpdateView):
    """ 
    Modifica la información de una determinada observacion
    """
    model = Turno
    form_class = FormularioTurno
    template_name = 'clinica/turnos/form_turno.html'
    success_url = reverse_lazy('pacientes:lista_turnos')

    def form_valid(self, form):
        registrarActividad(
            self.request,
            'Modificó un turno'
        )
        messages.success(
            self.request,
            'Turno modificado!'
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Turno para {self.object.paciente}'
        contexto['url_volver'] = self.success_url
        contexto['editar'] = True
        return contexto


class Eliminar(LoginRequiredMixin, generic.DeleteView):
    """
    Elimina un turno.
    """
    model = Turno
    template_name = 'componentes/delete.html'

    def get_success_url(self):
        registrarActividad(
            self.request,
            'Eliminó un turno'
        )
        messages.success(
            self.request,
            'Turno eliminado!'
        )
        return reverse_lazy('pacientes:lista_turnos')

    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['titulo'] = f'Eliminar el turno de {self.object.paciente}'
        contexto['url_volver'] = reverse_lazy('pacientes:lista_turnos')
        return contexto

class TurnosCalendarioView(View):
    def get(self, request, *args, **kwargs):
        # Recupera los turnos desde la base de datos
        turnos = Turno.objects.all()

        # Formatea los datos de los turnos para que coincidan con la estructura de eventos de FullCalendar
        eventos = []
        for turno in turnos:
            eventos.append({
                'title': turno.paciente.nombre,  # Título del evento 
                'start': turno.fecha.isoformat(),  # Fecha de inicio del evento en formato ISO
                'medico': turno.paciente.medico.nombre,
            })

        return JsonResponse(eventos, safe=False)

templates/clinica/pacientes/observaciones/form_observacion.html
{% extends 'layout.html' %}
{% load usuarios_tags %} 
{% load widget_tweaks %}

{% block content %}
    {% if user|sector:"Medico" or user|sector:"Gerencia" %}
        <div class="row">
            <form method="post">
                {% csrf_token %}
                <div class="container pt-3">
                    <h1 class="display-5 text-center my-3">{{titulo}}</h1>

                    {% include 'componentes/forms_errors.html' %}

                    <!-- Historial Medico -->
                    <div class="row d-flex justify-content-center">
                        <!-- Motivo -->
                        <div class="col-6">
                            <div class="my-3">
                                <label class="form-label">
                                    {{form.motivo_consulta.label|upper}}
                                </label>
                                {{form.motivo_consulta|attr:'autocomplete:off'|attr:'autofocus:on'|add_class:'form-control text-center rounded'}}
                            </div>
                        </div>
                    </div>

                    <!-- Especialidad -->
                    <div class="row d-flex justify-content-center">
                        <div class="col-3">
                            <div class="my-3">
                                <label class="form-label">{{form.especialidad.label|upper}}
                                    <!-- Texto de ayuda -->
                                    <small class="form-text text-muted">{{ form.especialidad.help_text }}</small>
                                </label>
                                {{form.especialidad|add_class:'form-control rounded'}}
                            </div>
                        </div>
                    </div>
                    
                    <!-- Tratamiento -->
                    <div class="row d-flex justify-content-center">
                        <div class="col-5">
                            <div class="my-3">
                                <label class="form-label">{{form.tratamientos.label|upper}}
                                    <!-- Texto de ayuda -->
                                    <small class="form-text text-muted">{{ form.tratamientos.help_text }}</small>
                                </label>
                                {{form.tratamientos|add_class:'form-control rounded'}}
                            </div>
                        </div>
                    </div>
                    <!-- Procedimientos -->
                    <div class="row d-flex justify-content-center">
                        <div class="col-5">
                            <div class="my-3">
                                <label class="form-label">{{form.procedimientos.label|upper}}
                                    <small class="form-text text-muted">{{ form.procedimientos.help_text }}</small>
                                </label>
                                {{form.procedimientos|add_class:'form-control rounded'}}
                            </div>
                        </div>
                    </div>

                    
                    <div class="d-flex justify-content-center">
                        <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
                            <a href="{{url_volver}}" type="button" class="btn btn-outline-primary">
                                <i class="fas fa-angle-double-left text-info"></i> Volver
                            </a>
                            <button type="submit" class="btn btn-outline-primary">
                                <i class="fas fa-check text-info"></i> Guardar
                            </button>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">No tienes permiso para cargar o modificar el historial de consultas</h1>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/clinica/pacientes/observaciones/lista_observaciones.html
{% extends 'layout.html' %}
{% load usuarios_tags %} 
{% load static %} 

{% block content %}
    {% if user|sector:"Medico" or user|sector:"Gerencia" %}
        <div class="d-flex justify-content-center my-4">
            <div class="btn-group shadow-sm" role="group" aria-label="Basic outlined example">
                <a href="{{volver}}" type="button" class="btn btn-outline-primary">
                    <i class="fas fa-angle-double-left text-info"></i> Volver
                </a>
                <a href="{% url 'pacientes:agregar_observacion' pacienteid %}" type="button" class="btn btn-outline-primary">
                    <i class="fas fa-plus text-info"></i> Agregar
                </a>
            </div>
        </div>

        <div class="row my-4 d-flex justify-content-center">
            <div class="col-md-8 mx-2">
                <div class="my-3 p-3 bg-white rounded shadow-lg">
                    <h6 class="border-bottom pb-2 mb-0">
                    {{titulo}}
                    {% if cantidad %}
                        <span class="badge bg-success rounded-pill align-text-bottom">{{cantidad}}</span>
                    {% endif %}
                    </h6>         
                    {% if Observaciones %}
                        {% for observacion in Observaciones %}
                            <h3 class="text-center my-3">
                                <span class="text-info">{{observacion.created_at|date:"SHORT_DATE_FORMAT"}}</span>
                                {{observacion.motivo_consulta}}
                                <a href="{% url 'pacientes:eliminar_observacion' observacion.id %}?lista={{pacienteid}}">
                                    <i class="fas fa-times text-danger mx-2 float-right"></i>
                                </a>
                                <a href="{% url 'pacientes:editar_observacion' observacion.id %}?paciente={{pacienteid}}" 
                                class="mx-2"> 
                                    <i class="fas fa-edit text-success mx-2 float-right"></i>
                                </a>
                            </h3>
                            <p>
                               
                                <div>{% if observacion.especialidad %}</div>
                                    
                                    <div>Especialidad: <h style="font-family: 'Arial', serif;">{{ observacion.especialidad }}</h></div>
                                    <div>
                                    Tratamientos: 
                                    {% if observacion.tratamientos %}<h style="font-family: 'Arial', serif;">{{ observacion.tratamientos }}</h>
                                    {% else %}
                                        No hay tratamientos ...
                                    {% endif %}
                                    </div>
                                    <div>
                                    Procedimientos: 
                                    {% if observacion.procedimientos %} <h style="font-family: 'Arial', serif;">{{ observacion.procedimientos }}</h>
                                    {% else %}
                                        No hay procedimientos aplicados ...
                                    {% endif %}
                                    </div>
                                {% else %}
                                    No hay más detalles...
                                {% endif %}
                            </p>

                        {% endfor %} 
                    {% else %}
                        <h1>No hay registros aun</h1>
                    {% endif %}
                </div>
            </div>
            {% if imagen %}
                <div class="col-md-4">
                    <img class="img-fluid rounded" src="{{imagen.url}}" alt="Imagen del paciente" height="250" width="250">
                </div>
            {% endif %}
    </div>
    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-8">
                <h1 class="text-center my-5 lead">No tienes permiso para ver las observaciones</h1>
            </div>
        </div>
    {% endif %}
{% endblock %}